# Generated by Django 5.1 on 2024-08-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(max_length=2048)),
                ('short_url', models.CharField(max_length=10, unique=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('expiry_time', models.IntegerField(help_text='Expiry time in minutes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
