# Generated by Django 5.1 on 2024-08-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
