# Generated by Django 5.1 on 2024-09-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_alter_url_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='alias',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=10),
        ),
    ]
