# Generated by Django 5.1 on 2024-10-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_alter_url_alias_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expiry_time',
            field=models.IntegerField(blank=True, help_text='Expiry time in minutes', null=True),
        ),
    ]
